#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
#!/bin/bash echo  echo rm -rf
~/bot-trading echo git clone 
https://github.com/joaquingonzalezotharan-spec/bot-trading.git ~/bot-trading echo cd ~/bot-trading || exit 1 echo python3 -m venv ~/venv_bot echo source ~/venv_bot/bin/activate echo python3 -m pip install --upgrade pip echo pip install pandas python-binance echo pip install requests python-dotenv echo pip install numpy pandas_ta echo  echo cat > /tmp/run_bot.sh <<EOF echo #!/bin/bash echo source ~/venv_bot/bin/activate echo cd ~/bot-trading echo python3 bot_futuros.py > /home/ubuntu/bot.log 2>&1 echo EOF echo chmod +x /tmp/run_bot.sh echo screen -dmS boteducativo /tmp/run_bot.sh echo  chmod +x desplegar.sh scp -i /.ssh/clave-tokio.pem desplegar.sh ubuntu@57.183.31.232: ssh -i /Users/admin/.ssh/clave-tokio.pem ubuntu@57.183.31.232 bash ~/desplegar.sh
